version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    command: >
      sh -c "python3 -m pip install --upgrade pip &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
